[이미지 채널 분리]
- opencv는 이미지 데이터 저장순서가 bgr
- 채널 분리 후 채널별 출력

In [ ]:
import seaborn as sns
import pandas as pd # 데이터 분석 및 전처리
import numpy as np # 숫자처리
import matplotlib.pyplot as plt # 데이터 시각화
import cv2
import os

In [2]:
imgDir = '../_data/_image/'
videoDir = '../_data/_video/'
fileName = 'image_fx_ (1).jpg'

In [3]:
colorImg = cv2.imread(imgDir+fileName, cv2.IMREAD_COLOR)
if colorImg is not False:
    print(fileName)
    print(f"shape: {colorImg.shape}     ndim: {colorImg.ndim}")
else:
    print(f'{colorImg} check')

image_fx_ (1).jpg
shape: (768, 1408, 3)     ndim: 3


In [4]:
colorImg_b, colorImg_g, colorImg_r = cv2.split(colorImg)
import time
cv2.waitKey(0)
cv2.imshow(f"[Blue Channel]", colorImg_b)
time.sleep(1)
cv2.imshow(f"[Green Channel]", colorImg_g)
time.sleep(1)
cv2.imshow(f"[Red Channel]", colorImg_r)

cv2.waitKey(0)
cv2.destroyWindow(f"[Blue Channel]")
time.sleep(1)
cv2.destroyWindow(f"[Green Channel]")
time.sleep(1)
cv2.destroyWindow(f"[Red Channel]")
time.sleep(1)


In [5]:
print(colorImg_b)

[[133 129 132 ... 100 101  99]
 [138 134 135 ... 101 100  99]
 [135 133 135 ... 102 102 101]
 ...
 [107 109 107 ... 104 105 106]
 [106 107 107 ... 106 106 105]
 [107 109 106 ... 104 104 106]]


In [ ]:
print(f"[Blue Channel] shape: {colorImg_b.shape}     ndim: {colorImg_b.ndim}")
print(f"[Green Channel] shape: {colorImg_g.shape}     ndim: {colorImg_g.ndim}")
print(f"[Red Channel] shape: {colorImg_r.shape}     ndim: {colorImg_r.ndim}")

[Blue Channel] shape: (768, 1408)     ndim: 2
[Green Channel] shape: (768, 1408)     ndim: 2
[Red Channel] shape: (768, 1408)     ndim: 2


[4] 채널 병합

In [9]:
img_rgb = cv2.merge((colorImg_r, colorImg_g, colorImg_b))
cv2.imshow('[RGB]', img_rgb)
cv2.imshow('[BGR]', colorImg)
cv2.waitKey()
cv2.destroyAllWindows()
