In [5]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures


In [6]:
X = np.arange(6).reshape(3, 2)
X



array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
poly = PolynomialFeatures(2)
                        #차수
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [8]:
poly = PolynomialFeatures(interaction_only=True)
                        # 제곱은 안하고 곱한 값만 골라서 feature 생성.
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

최적 차수 찾기
- feature extraction
- feture selection 
- PolynomialFeatures(n)
    - n차수 컬럼 생성.


과대적합
- 훈련 데이터 셋에만 점수가 잘나오고 테스트에는 부적합.
- 원인: 너무 많은 피쳐.
- 커스터마이징을 심하게 하여 대중성 손실 느낌.
- 테스트 데이터가 결과다 
- fit()은 수정할수 있는 범위가 한정.
- 피처 범위 및 개수로 데이터 조정.
cost = 오차
