[ mnist Custom Model Class 정의 및 설계]
- 데이테셋 및 구현방법에 따른 모델 설계
- 부모클래스 : nn.Module
- 필수 오버라이딩 메서드 : 상속 받은 메서드 중 재정의하는 것
    *  _ _init_ _(self)   : 모델 구조/구성 요소 정의 
    * forward(self, data) : 전방향/순방향 학습 기능 메서드

[1] 모듈 로딩 <hr>

In [2]:
import torch                        # tensor, 내장함수 및 클래스 관련 모듈
import torch.nn as nn               # 인공신경망 관련 층, 함수 클래스 모듈
import torch.nn.functional as F     # 인공신경망 관련 층, AF, LF 함수 모듈

import pandas as pd                 # 데이터 로딩 및 전처리 관련 모듈 
import numpy as np                  # raw 데이터 즉, ndarray 데이터 관련 모듈


[2] 커스텀 모델 클래스 설계 <hr>

In [24]:
## [2-1] 고정된 층과 퍼셉트론 구성 모델
## - 데 이  터 셋 : 피쳐 3 , 타겟 1 , 타겟 연속형
## - 학습    방법 : 지도학습 - 회귀
## - 구현알고리즘 : 인공신경망계열 DNN 
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      3        """ 20                ReLU            => 각 개인이 알아서. 
## - 은닉층      20       10                ReLU                
## - 은닉층      10        5                ReLU
## - 출력층       5  """       1                 -
## -------------------------------------------------
""" 
데이터셋 mnist: 피쳐 4, 타겟 1. 타겟은 범주형 3가지
학습 방법은 : 범주형이므로 분류 - 
구현알고리즘: 인공신경망 DNN
	  입력        퍼셉트론    활성화함수
입력층 4(피쳐4)   8(퍼셉트론)  RELU
은닉충  8           8 		RELU
은닉충  8           8 		RELU
은닉충  8           8 		RELU
출력층  8	    	3		
"""

class Cutom_mnist_Model(nn.Module):
    # 인스턴스 초기화 및 생성 메서드
    def __init__(self):
        super().__init__() #부모(nn.Module)의 init 생성
        print('__init__()')
        self.in_layer=nn.Linear(784, 400)  #input, output
        self.hd_layer1=nn.Linear(400, 200)        # 히든1
        self.hd_layer2=nn.Linear(200, 100)         # 히든2
        self.hd_layer3=nn.Linear(100, 50)         # 히든3
        self.out_layer=nn.Linear(50, 10)

    # 순전파 학습 메서드 
    def forward(self, data):
        #- 입력층
        out=self.in_layer(data)      # data * weight + b
        out=F.relu(out)              # AF(data * weight + b) 결과물
                                     # 은닉으로 넘겨줌.

        #- 은닉층1
        out=self.hd_layer1(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물        

        #- 은닉층2
        out=self.hd_layer2(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물    

        #- 은닉층3
        out=self.hd_layer3(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물    
        
        
        #- 출력층 : 회귀로 결과 그라드 반환
        out=self.out_layer(out)      # out * weight + b

        return out 
               

In [25]:
## - 모델 사용 -----------------------------------
## 모델 인스턴스 생성 
model=Cutom_mnist_Model()

## 모델 구조 확인
print(model)

__init__()
Cutom_mnist_Model(
  (in_layer): Linear(in_features=784, out_features=400, bias=True)
  (hd_layer1): Linear(in_features=400, out_features=200, bias=True)
  (hd_layer2): Linear(in_features=200, out_features=100, bias=True)
  (hd_layer3): Linear(in_features=100, out_features=50, bias=True)
  (out_layer): Linear(in_features=50, out_features=10, bias=True)
)


In [26]:
# data load
trainDF = pd.DataFrame(pd.read_csv('../_data/mnist/train.csv'))
testDF = pd.DataFrame(pd.read_csv('../_data/mnist/t10k.csv'))
trainDF.head()
trainDF.shape
sorted(trainDF['5'].unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [27]:
trainDF.head()

,5,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.608,0.609,0.610,0.611,0.612,0.613,0.614,0.615,0.616,0.617
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [28]:
## 모델 동작 테스트
data=torch.FloatTensor(trainDF.iloc[:,1:].values )
# data=torch.FloatTensor(iris_encodeDF.values)
print(data)

## 모델에 데이터 전달
pre=model(data)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [29]:
# 모델에 파라미터들
for name, param in model.named_parameters():
    print(name, param)                  ## 위에서 입력한 퍼셉트론의 수 만큼 weight와 bias 반환.

in_layer.weight Parameter containing:
tensor([[-0.0160, -0.0295,  0.0120,  ...,  0.0172, -0.0045,  0.0185],
        [-0.0218, -0.0074,  0.0122,  ...,  0.0031,  0.0329,  0.0327],
        [-0.0333, -0.0252,  0.0249,  ..., -0.0303, -0.0146, -0.0345],
        ...,
        [ 0.0031, -0.0326,  0.0274,  ...,  0.0167,  0.0306,  0.0239],
        [-0.0091, -0.0120,  0.0291,  ..., -0.0100,  0.0338, -0.0153],
        [-0.0233,  0.0144,  0.0165,  ...,  0.0316,  0.0038,  0.0245]],
       requires_grad=True)
in_layer.bias Parameter containing:
tensor([-4.6345e-03, -1.4284e-02, -2.2836e-02, -1.3595e-02, -1.1757e-02,
        -2.6199e-02, -1.0747e-02, -2.2595e-02,  3.1736e-02,  3.0655e-02,
         3.0502e-02,  2.6856e-02, -9.2484e-03,  6.2589e-03,  2.4914e-02,
        -1.0586e-02,  3.0705e-02, -5.8168e-03, -2.4084e-02, -9.7674e-04,
         1.2734e-02,  2.8720e-02, -1.0170e-02, -7.5041e-03,  7.7773e-03,
         2.3319e-02,  3.4547e-02, -9.1677e-03,  5.9186e-03, -3.2676e-02,
         9.5486e-03,  1.769

In [30]:
model

Cutom_mnist_Model(
  (in_layer): Linear(in_features=784, out_features=400, bias=True)
  (hd_layer1): Linear(in_features=400, out_features=200, bias=True)
  (hd_layer2): Linear(in_features=200, out_features=100, bias=True)
  (hd_layer3): Linear(in_features=100, out_features=50, bias=True)
  (out_layer): Linear(in_features=50, out_features=10, bias=True)
)