[ Custom Model Class 정의 및 설계]
- 데이테셋 및 구현방법에 따른 모델 설계
- 부모클래스 : nn.Module
- 필수 오버라이딩 메서드 : 상속 받은 메서드 중 재정의하는 것
    *  _ _init_ _(self)   : 모델 구조/구성 요소 정의 
    * forward(self, data) : 전방향/순방향 학습 기능 메서드

[1] 모듈 로딩 <hr>

In [2]:
import torch                        # tensor, 내장함수 및 클래스 관련 모듈
import torch.nn as nn               # 인공신경망 관련 층, 함수 클래스 모듈
import torch.nn.functional as F     # 인공신경망 관련 층, AF, LF 함수 모듈

import pandas as pd                 # 데이터 로딩 및 전처리 관련 모듈 
import numpy as np                  # raw 데이터 즉, ndarray 데이터 관련 모듈


[2] 커스텀 모델 클래스 설계 <hr>

In [3]:
## [2-1] 고정된 층과 퍼셉트론 구성 모델
## - 데 이  터 셋 : 피쳐 3 , 타겟 1 , 타겟 연속형
## - 학습    방법 : 지도학습 - 회귀
## - 구현알고리즘 : 인공신경망계열 DNN 
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      3        20                ReLU
## - 은닉층      20       10                ReLU
## - 은닉층      10        5                ReLU
## - 출력층       5        1                 -
## -------------------------------------------------
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      3        """ 20                ReLU            => 각 개인이 알아서. 
## - 은닉층      20       10                ReLU                
## - 은닉층      10        5                ReLU
## - 출력층       5  """       1                 -
## -------------------------------------------------
class CutomModel(nn.Module):
    # 인스턴스 초기화 및 생성 메서드
    def __init__(self):
        super().__init__() #부모(nn.Module)의 init 생성
        print('__init__()')
        self.in_layer=nn.Linear(3, 20)  #input, output
        self.hd_layer1=nn.Linear(20, 10)        # 히든1
        self.hd_layer2=nn.Linear(10, 5)         # 히든2
        self.out_layer=nn.Linear(5, 1)

    # 순전파 학습 메서드 
    def forward(self, data):
        #- 입력층
        out=self.in_layer(data)      # data * weight + b
        out=F.relu(out)              # AF(data * weight + b) 결과물
                                     # 은닉으로 넘겨줌.

        #- 은닉층1
        out=self.hd_layer1(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물        

        #- 은닉층2
        out=self.hd_layer2(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물    

        #- 출력층 : 회귀로 결과 그래도 반환
        out=self.out_layer(out)      # out * weight + b

        return out 
               

In [4]:
## - 모델 사용 -----------------------------------
## 모델 인스턴스 생성 
model=CutomModel()

## 모델 구조 확인
print(model)

__init__()
CutomModel(
  (in_layer): Linear(in_features=3, out_features=20, bias=True)
  (hd_layer1): Linear(in_features=20, out_features=10, bias=True)
  (hd_layer2): Linear(in_features=10, out_features=5, bias=True)
  (out_layer): Linear(in_features=5, out_features=1, bias=True)
)


In [5]:
## 모델 동작 테스트
data=torch.FloatTensor([[10,5,8],[5,9,7]])
print(data)

## 모델에 데이터 전달
pre=model(data)

tensor([[10.,  5.,  8.],
        [ 5.,  9.,  7.]])


In [6]:
# 모델에 파라미터들
for name, param in model.named_parameters():
    print(name, param)                  ## 위에서 입력한 퍼셉트론의 수 만큼 weight와 bias 반환.

in_layer.weight Parameter containing:
tensor([[-0.2981,  0.3434,  0.0439],
        [ 0.5679, -0.2520,  0.1467],
        [ 0.5222,  0.0563,  0.1806],
        [-0.2243,  0.1499, -0.4562],
        [ 0.4748,  0.5367, -0.2286],
        [-0.1018,  0.2129, -0.3735],
        [ 0.0161, -0.1487,  0.0542],
        [ 0.3141, -0.0008,  0.1535],
        [ 0.3994, -0.0147,  0.3736],
        [ 0.2952, -0.5405, -0.2661],
        [ 0.0752, -0.1246,  0.1729],
        [ 0.0339,  0.2618,  0.5682],
        [-0.2830,  0.4277,  0.4063],
        [-0.2853,  0.4370,  0.1921],
        [-0.0337,  0.1821,  0.2764],
        [-0.0057, -0.5109, -0.3262],
        [-0.5025, -0.0157, -0.0975],
        [-0.1881, -0.1658, -0.1542],
        [-0.0676, -0.3733,  0.2515],
        [ 0.2984, -0.3431, -0.2907]], requires_grad=True)
in_layer.bias Parameter containing:
tensor([-0.4333, -0.2105,  0.5224, -0.1628, -0.2257,  0.2353,  0.4100,  0.5468,
         0.0461, -0.4103, -0.3123, -0.3303, -0.5212, -0.4357,  0.0634, -0.1767,
     