#### [ linear Layer ]
- pytorch 에서 퍼셉트론의 가중치합계(Weighted Sum) 을 계산해주는 층 클래스
- 출력값에 활성화함수(AF) 적용해야 출력값이 됨

[1] 모듈로딩 <hr>

In [15]:
import torch               
#텐서 관련 모듈

import torch.nn as nn
# 신경망 관련 모듈

import torch.nn.functional as F
# 활성화 및 신경망 관련 함수들

In [32]:
#임시데이터
X_train  = torch.randn(2,4)
y_train  = torch.randint(1,5,(2,1))


In [33]:
print( X_train.shape, y_train.shape)

torch.Size([2, 4]) torch.Size([2, 1])


[2] 선형결합층(Full-Connected Layer : FC Layer)

In [37]:
## 인스턴스 생성
layer = nn.Linear(4,3)     # 입력 피쳐 수, 출력 결과 수 =  퍼셉트론 수

#

In [38]:
## 가중치 합 계산
output = layer(X_train)
output

tensor([[ 0.2397,  0.1777, -1.3904],
        [ 0.9815,  1.0119,  0.7123]], grad_fn=<AddmmBackward0>)

In [ ]:
## W, b 텐서 확인
# 퍼셉트론 개수만큼 결과를 뱉어냄.
print(f"weight => {layer.weight}")
print(f"bias => {layer.bias}")

weight => Parameter containing:
tensor([[-0.0460, -0.2409, -0.0826, -0.3451],
        [-0.0918, -0.2939, -0.2338, -0.2425],
        [ 0.4492, -0.4019,  0.1312,  0.4201]], requires_grad=True)
bias => Parameter containing:
tensor([0.3526, 0.2896, 0.0048], requires_grad=True)
