#### [ TEST - TENSOR ]

In [2]:
## 모듈로딩
import torch 
import numpy as np 

[1] 10 ~ 100 사이 5.5 간격의 데이터로 구성된 3차원 텐서 생성하세요.

In [19]:
ex1 = torch.tensor(np.arange(10,100,5.5))
ex1.reshape(17,1,1)

# np.linspace(10,100,retstep=5.5)


tensor([[[10.0000]],

        [[15.5000]],

        [[21.0000]],

        [[26.5000]],

        [[32.0000]],

        [[37.5000]],

        [[43.0000]],

        [[48.5000]],

        [[54.0000]],

        [[59.5000]],

        [[65.0000]],

        [[70.5000]],

        [[76.0000]],

        [[81.5000]],

        [[87.0000]],

        [[92.5000]],

        [[98.0000]]], dtype=torch.float64)

[2] 정규분포를 띠는 2D 랜덤 텐서를 생성하세요.(매번 동일한 랜덤값 유지)

In [ ]:
np.lins

In [115]:
ex2 = torch.Tensor(np.linspace(0,1))
ex2.reshape(-1,2)

tensor([[0.0000, 0.0204],
        [0.0408, 0.0612],
        [0.0816, 0.1020],
        [0.1224, 0.1429],
        [0.1633, 0.1837],
        [0.2041, 0.2245],
        [0.2449, 0.2653],
        [0.2857, 0.3061],
        [0.3265, 0.3469],
        [0.3673, 0.3878],
        [0.4082, 0.4286],
        [0.4490, 0.4694],
        [0.4898, 0.5102],
        [0.5306, 0.5510],
        [0.5714, 0.5918],
        [0.6122, 0.6327],
        [0.6531, 0.6735],
        [0.6939, 0.7143],
        [0.7347, 0.7551],
        [0.7755, 0.7959],
        [0.8163, 0.8367],
        [0.8571, 0.8776],
        [0.8980, 0.9184],
        [0.9388, 0.9592],
        [0.9796, 1.0000]])

[3] 임의의 정수값으로 구성된 3차원 텐서를 아래 조건 만족하도록 생성하세요.
- 조건
    * 형태 : 10행 10열 3개
    * 타입 : 0 ~ 255값 저장되는 최소 크기 타입
    * 생성 후 3개 2D 텐서로 분리 저장

In [93]:
ex3 = torch.tensor( np.linspace(0,1,300)*255, dtype=torch.uint8)
ex3 = ex3.reshape(10,10,3)

ex31 = ex3[:,:,0]
ex32 = ex3[:,:,1]
ex33 = ex3[:,:,2]



[4] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 형변환으로 2D 텐서 생성 T2
- T1의 형변환으로 3D 텐서 생성 T3
- T1의 형변환으로 4D 텐서 생성 T4

In [50]:
t1 = torch.tensor(np.arange(3,37,3))

t2 = t1.reshape(2,6)
t3 = t1.reshape(2,6,1)
t4 = t1.reshape(2,2,3,1)

[5] 아래 2개 텐서에 대한 연산 수행 결과 출력하세요.
- t1 :  [[11,22], [33,44]]
- t2 :  [3,4,5]
- 연산 : 덧셈, 뺄셈, 곱셈, 나눗셈 연산자와 메서드

In [65]:
t1 =  torch.tensor([[11,22], [33,44]])
t2 =  torch.tensor([3,4,5])
t1 = t1.reshape(4,1)
t2 = t2.reshape(1,3)
print(t1.add(t2))
print(t1.sub(t2))

print(t1.matmul(t2))
print(t1.div(t2))


tensor([[14, 15, 16],
        [25, 26, 27],
        [36, 37, 38],
        [47, 48, 49]])
tensor([[ 8,  7,  6],
        [19, 18, 17],
        [30, 29, 28],
        [41, 40, 39]])
tensor([[ 33,  44,  55],
        [ 66,  88, 110],
        [ 99, 132, 165],
        [132, 176, 220]])
tensor([[ 3.6667,  2.7500,  2.2000],
        [ 7.3333,  5.5000,  4.4000],
        [11.0000,  8.2500,  6.6000],
        [14.6667, 11.0000,  8.8000]])


[6] 텐서의 행렬곱 결과 출력
- t1 : 원소 10개
- t2 : 원소 5개
- 연산: 메서드

In [68]:
t1 = torch.Tensor(range(0,10))
t2 = torch.Tensor(range(5))
t1 = t1.reshape(10,1)
t2 = t2.reshape(1,5)

t1.matmul(t2)


tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.],
        [ 0.,  2.,  4.,  6.,  8.],
        [ 0.,  3.,  6.,  9., 12.],
        [ 0.,  4.,  8., 12., 16.],
        [ 0.,  5., 10., 15., 20.],
        [ 0.,  6., 12., 18., 24.],
        [ 0.,  7., 14., 21., 28.],
        [ 0.,  8., 16., 24., 32.],
        [ 0.,  9., 18., 27., 36.]])

[7] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 축 추가로 2D 텐서 생성 T2
- T1의 축 추가로 3D 텐서 생성 T3
- T1의 축 추가로 4D 텐서 생성 T4

- T4의 축 축소로 3D 텐서 생성 T5
- T3의 축 축소로 2D 텐서 생성 T6
- T2의 축 축소로 1D 텐서 생성 T7

In [ ]:
t1 = torch.tensor(range(10))
t2 = t1.unsqueeze(1)
t3 = t2.unsqueeze(1)
t4 = t3.unsqueeze(1)
t5 = t4.squeeze(1)
t6 = t3.squeeze(1)
t7 = t2.squeeze(1)






torch.Size([10, 1, 1])