#### 사용자 정의 데이터셋(Custom Dataset)<hr>

- torch.utils.data.Dataset을 상속받아 직접 커스텀 데이터셋(Custom Dataset) 생성
- torch.utils.data.Dataset은 미완성의 추상클래스(Abstract Class)
   * 반드시 구현해야 하는 메서드 존재
   * def  \_\_init\_\_(self): 데이터셋 전처리 / 초기화 메서드
   * def \_\_len\_\_(self): 데이터셋 길이 즉 샘플 수 반환 메서드
   * def \_\_getitem\_\_(self,idx): idx 해당 데이터 1개 반환하는 메서드

In [43]:
# 모듈로딩
import torch                                        # 텐서 및 기본 텐서 제어 함수들 모듈
import torch.nn.functional as F                     # 인공신경망 관련 함수들
from torch.utils.data import Dataset                # 인공신경망 데이터 관련 클래스 및 함수들
from torch.utils.data import DataLoader             # 인공신경망 데이터 관련 클래스 및 함수들

In [60]:
## Custom Dataset 생성
class CustomDataset(Dataset):
    # 데이터 초기화
    def __init__ (self):
        self.x_data = [ [73, 80, 75], 
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70] ]
        self.y_data = [[152], [185], [180], [196], [142]]
    # 총 데이터의 개수 리턴
    def __len__ (self): 
        # print('__len__()')
        return len(self.x_data)
    
    # 인덱스에 해당하는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__ (self, idx):
        print('__getitem__()', idx)
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [38]:
# Dataset 객체 생성
dataset = CustomDataset()


In [39]:
# Dataset 객체 확인
len(dataset)
dataset[1]



__len__()
__getitem__() 1


(tensor([93., 88., 93.]), tensor([185.]))

- DateaLoader로 데이터로딩 <hr>

In [53]:
dLoader = DataLoader(dataset, batch_size=2)

In [54]:
#dataLoader 객체 속성들
dLoader.batch_size
## - 학습에 사용할 데이터셋 dLoader.dataset
dLoader.dataset.y_data
## 데이터 추출
for feature, label in dLoader:
    print(feature, label)
    break

__len__()
__getitem__() 0
__getitem__() 1
tensor([[73., 80., 75.],
        [93., 88., 93.]]) tensor([[152.],
        [185.]])


In [62]:
dLoader = DataLoader(dataset, 
                     batch_size=3,          # 한번에 학습할 데이터 갯수
                     shuffle=True)          # 데이터셋 섞기

__len__()
__len__()


In [64]:
#dataLoader 객체 속성들
dLoader.batch_size
## - 학습에 사용할 데이터셋 dLoader.dataset
dLoader.dataset.y_data
## 데이터 추출
for feature, label in dLoader:
    print(feature, label)
    print('-'*39)

__len__()
__len__()
__getitem__() 4
__getitem__() 1
__getitem__() 0
tensor([[73., 66., 70.],
        [93., 88., 93.],
        [73., 80., 75.]]) tensor([[142.],
        [185.],
        [152.]])
---------------------------------------
__len__()
__getitem__() 3
__getitem__() 2
tensor([[ 96.,  98., 100.],
        [ 89.,  91.,  90.]]) tensor([[196.],
        [180.]])
---------------------------------------
