#### [ Tensor & Numpy 집계함수]

In [1]:
import numpy as np
import torch


by numpy

In [2]:
data = np.array([[11,22,33], [44,11,55]])
data

array([[11, 22, 33],
       [44, 11, 55]])

In [ ]:
print(data.max())
print(data.max(axis=0)) ## 세로축 중에서 젤 높은것.
print(data.max(axis=1))## 가로 축 중에서 . 

55
[44 22 55]
[33 55]


In [6]:
## ndarray에서 큰 값의 인덱스 찾기.
print(data.argmax())
print(data.argmax(axis=0))
print(data.argmax(axis=1))

5
[1 0 1]
[2 2]
