#### [ Tensor Indexing and Slicing ]
    

[1] 모듈 로딩 <hr>

In [1]:
import torch

In [2]:
## 텐서 생성
t1 = torch.linspace(1,10,6)
t1

tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

In [3]:
## 인덱싱
t1[0], t1[-1]

(tensor(1.), tensor(10.))

In [4]:
#여러개 원소 읽기
t1[[1,-1]]

tensor([ 2.8000, 10.0000])

In [6]:
## 슬라이싱
t1[1:]

tensor([ 2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

In [8]:
# cas1 : 같은 크기 행렬
m1 = torch.FloatTensor([[3,4]])
m2 = torch.FloatTensor([[2,5]])
m3 = m1+m2
print( m3, m3.shape   )

tensor([[5., 9.]]) torch.Size([1, 2])


In [9]:
# cas1 : 벡터와 행렬
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m3 = m1+m2
print( m3, m3.shape   )

tensor([[4., 5.]]) torch.Size([1, 2])


In [10]:
# Case 3 : 크기 다른 두 개 행렬
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
m3 = m1 + m2
print(m3, m3.shape)

tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


In [12]:
# 원소 곱셈 mul() – element-wise
m1 = torch.FloatTensor([[1, 2], [3, 4]])  # 22
m2 = torch.FloatTensor([[1], [2]])         #1 2
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print( m1 * m2 ) # 2 x 2
print( m1.mul( m2 ) )

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [25]:
# view() 메서드
t2=torch.tensor([[1,2,3,], [4,54,56]])
print( t2.shape )
t2.view(3,2)
print( t2.shape )
#  원소의 수를 유지하면서 텐서의 크기 변경
#  numpy의 reshape()와 동일한 기능
t2 = torch.tensor([[5,6,7,8], [3, 45, 87,44]])
print( t2.shape)
t2.view(2,2,2)
# print( t2.view(2,2,2))
print(t2.shape)
# print(t2)



torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 4])
torch.Size([2, 4])
