#### [ Tensor 생성 및 속성 확인 ]
- Tensor란? 
    * pytorch에서 데이터 저장 및 모델 입출력 데이터 저장 타입
    

[1] 모듈 로딩 <hr>

In [4]:
import torch

In [5]:
torch.manual_seed(12)

t5 = torch.rand(2,3)    # 0, 1 분포 안에서 랜덤생성
t6 = torch.rand(2,3)    # standard normal 분포 안에서 랜덤 생성

t7 = torch.randint(low=1, high=10, size=(2,3)) # low, high  low<= 값 <high

In [14]:
from utils import *
import numpy as np

In [15]:

printTensorInfo('t5', t5)
printTensorInfo('t6', t6)
printTensorInfo('t7', t7)

t5---------------------------------------
 shape  : torch.Size([2, 3])    torch.Size([2, 3])
 ndim   : 2       2
 device : cpu
 dtype  :  torch.float32
 data   :  tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
t6---------------------------------------
 shape  : torch.Size([2, 3])    torch.Size([2, 3])
 ndim   : 2       2
 device : cpu
 dtype  :  torch.float32
 data   :  tensor([[0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])
t7---------------------------------------
 shape  : torch.Size([2, 3])    torch.Size([2, 3])
 ndim   : 2       2
 device : cpu
 dtype  :  torch.int64
 data   :  tensor([[5, 3, 7],
        [4, 2, 8]])


In [ ]:
arr = np.linspace(1, 10, 6) # ndarray 객체
t1 = torch.from_numpy( arr ) # sharing
t2 = torch.as_tensor( arr ) # sharing
t3 = torch.tensor( arr ) # copy

In [18]:
printTensorInfo('t1', t1)
printTensorInfo('t2', t2)
printTensorInfo('t3', t3)

t1---------------------------------------
 shape  : torch.Size([6])    torch.Size([6])
 ndim   : 1       1
 device : cpu
 dtype  :  torch.float64
 data   :  tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t2---------------------------------------
 shape  : torch.Size([6])    torch.Size([6])
 ndim   : 1       1
 device : cpu
 dtype  :  torch.float64
 data   :  tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t3---------------------------------------
 shape  : torch.Size([6])    torch.Size([6])
 ndim   : 1       1
 device : cpu
 dtype  :  torch.float64
 data   :  tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)


In [19]:
## 체크 1!
print(f"[전] arr => {arr}")
arr[0] = 5.0
print(f"[후] arr => {arr}")

[전] arr => [ 1.   2.8  4.6  6.4  8.2 10. ]
[후] arr => [ 5.   2.8  4.6  6.4  8.2 10. ]


In [24]:
print('t1 =>', t1)  # from_numpy  => 원본 공유, 같이 변경
print('t2 =>', t2)  # as_tensor   => 원본 공유, 같이 변경
print('t3 =>', t3)  # 새로운 객체

t1 => tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t2 => tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t3 => tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)


In [26]:
## Tensor 데이터 ==> Tensor 생성
t0 = torch.Tensor([11,22])

# t1 = torch.from_numpy(t0)
t2 = torch.as_tensor(t0)       # share 방식 => 공유 하기.
t3 = torch.tensor(t0)          # copy  방식 => 새로운 메모리공간에 데이터 복사.



C:\Users\kdt\AppData\Local\Temp\ipykernel_38408\2084629879.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t3 = torch.tensor(t0)          # copy  방식 => 새로운 메모리공간에 데이터 복사.


In [30]:
## 텐서 원소 변경
print(t0[0], t0[1])
print(t0[0].item(), t0[1])

tensor(11.) tensor(22.)
11.0 tensor(22.)


In [33]:
t0[0] = 9
print(t0[0].item())

9.0


In [35]:
# as_tensor() share로 원본 변경 시 적용 or
# copy 는 원본과 별개의 객체
print(t2, t3)

tensor([ 9., 22.]) tensor([11., 22.])


[4] 특정 데이터 타입의 Tensor를 생성
<hr>

In [ ]:
t1 = torch.FloatTensor([11,33])
print(t1, t1.dtype, sep='\n')

tensor([11., 33.])
torch.float32


In [39]:
t1 = torch.DoubleTensor([11,33])
print(t1, t1.dtype, sep='\n')

tensor([11., 33.], dtype=torch.float64)
torch.float64


In [41]:
t1 = torch.BoolTensor([11,0])
print(t1, t1.dtype, sep='\n')

tensor([ True, False])
torch.bool


In [ ]:
t1=torch.FloatTensor([1,2])
t2=torch.IntTensor([11,22])
t3=torch.DoubleTensor([1,2])
t4=torch.CharTensor([1,2])
t5=torch.LongTensor([1,2])
t6=torch.BoolTensor([1,2,0])

t7=torch.Tensor([1,2,0])
t8=torch.Tensor([1.,2,0])