[ Tensor shape 변경 ]

In [2]:
import torch


In [3]:
ten1=torch.tensor([11,22,33,44,55,66])
ten2=ten1.reshape(-1,1,1) # -1 의미 : 원소 개수에 맞게 알아서 배정
                # 3개 이므로 3차원.
print(ten2, ten2.ndim)
ten3=ten2.reshape(-1) # 1차원으로 펴기.
print(ten3, ten3.ndim)

tensor([[[11]],

        [[22]],

        [[33]],

        [[44]],

        [[55]],

        [[66]]]) 3
tensor([11, 22, 33, 44, 55, 66]) 1


In [4]:
# shape 변경 => reshape()
t1 = torch.tensor([11,22,33,44,55,66])
t2 = t1.reshape(-1, 1, 1)
t2.shape

torch.Size([6, 1, 1])

In [5]:
## t1 1D ==> 4D, t3 저장하기
t3 = t1.reshape(-1,1,1,1)
t3.shape

torch.Size([6, 1, 1, 1])

In [6]:
## shape 변경 ==> view()-----------
t2 = t1.view(2,3)
t2.shape

torch.Size([2, 3])

In [7]:
t3 = t1.view(-1,2,3)
t3.shape, t1.shape

# 공유하지 않음.

(torch.Size([1, 2, 3]), torch.Size([6]))

[ Axis 변경 ]

- axis란?
    * Tensor 의 shape 정보에서 확인
    * 2D => (m,n) => axis0 m, axis1 n
    * 3D => (l,m,n) => axis0 l, axis1 m, axis2 n

In [8]:
### 
"""  transpose() 메서드 """
t1 = torch.tensor([[11,22, 33]  , [33,44, 55]])
t2 = torch.tensor([[[11,22, 33]  , [33,44, 55] ]])

print( t1.shape, t1, sep='\n')


torch.Size([2, 3])
tensor([[11, 22, 33],
        [33, 44, 55]])


In [9]:
# => 0번축 <- 1번 축 변경
t1.transpose(1, 0 )

tensor([[11, 33],
        [22, 44],
        [33, 55]])

In [10]:
print( t2.shape, t2, sep='\n')
t3 = t2.transpose(1,0)
t3

torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [33, 44, 55]]])


tensor([[[11, 22, 33]],

        [[33, 44, 55]]])

In [11]:
print( t2.shape, t2, sep='\n')
t4 = t2.transpose(2,0)

# shape (1, 2, 3) => ( 3, 2, 1)

print( t4.shape, t4, sep='\n')

torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [33, 44, 55]]])
torch.Size([3, 2, 1])
tensor([[[11],
         [33]],

        [[22],
         [44]],

        [[33],
         [55]]])


In [12]:
""" permute() 메서드
모든 축 axis 변경 가능
"""
print( t2.shape, t2, sep='\n')

t3 = t2.permute(1, 2, 0)
print( t3.shape, t3, sep='\n')

torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [33, 44, 55]]])
torch.Size([2, 3, 1])
tensor([[[11],
         [22],
         [33]],

        [[33],
         [44],
         [55]]])


- 원소 갯수를 유지하며 차원 줄이기 

In [13]:
#이미지 1장. 가로, 세로 5 흑백 (5, 5, 1)
# - 형태 : (5,5,1)
# - 원소 : 5*5*1 = 25

t1 = torch.arange(11,36)
t1.shape

torch.Size([25])

In [14]:
t2 = t1.reshape(5,5,1)
t2.shape

torch.Size([5, 5, 1])

In [15]:
t3 = t2.transpose(0,2)
t3.shape

torch.Size([1, 5, 5])

In [16]:
t2.permute(2,1,0).shape

torch.Size([1, 5, 5])

In [17]:
"""  원소 갯수 유지하면서 3D ==> 2D  """
t4 = t3.squeeze()
t4.shape

torch.Size([5, 5])

In [18]:
""" 원소 갯수 유지하면서 2D => 3D  """
t4.unsqueeze(2).shape

torch.Size([5, 5, 1])

In [19]:
t4.squeeze_()

tensor([[11, 16, 21, 26, 31],
        [12, 17, 22, 27, 32],
        [13, 18, 23, 28, 33],
        [14, 19, 24, 29, 34],
        [15, 20, 25, 30, 35]])

In [20]:
t4.shape

torch.Size([5, 5])

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 3)