In [1]:
##p56

import cv2

In [2]:
img = cv2.imread('../_data/_image/Balatro-Cover.jpg')
type(img)

numpy.ndarray

In [3]:
img.ndim, img.shape, img.size

(3, (720, 1280, 3), 2764800)

In [4]:
img.dtype, img.itemsize

(dtype('uint8'), 1)

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a.dtype, a.shape

(dtype('int64'), (4,))

In [8]:
b = np.array([1,2,3,4], [5,6,7,8])
b.shape

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [ ]:
c = np.array([1,2,3.14,4])
c.dtype

dtype('float64')

In [ ]:
d = np.array([1,2,3,4], dtype=np.float32)
d

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
a=np.uint8([1,2,3,4])

In [ ]:
a = np.empty((2,3))

In [ ]:
a, a.dtype

(array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [1.78019082e-306, 1.89146896e-307, 7.56571288e-307]]),
 dtype('float64'))

In [ ]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [ ]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.zeros((2,3), dtype=np.int8)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
d = np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
e= np.full((2,3), 255)
e

array([[255, 255, 255],
       [255, 255, 255]])

In [ ]:
img, img.shape

(array([[[57, 51, 38],
         [20, 17,  2],
         [22, 24,  5],
         ...,
         [ 2,  2, 80],
         [ 4,  3, 69],
         [31, 31, 91]],
 
        [[28, 25, 11],
         [23, 23,  7],
         [27, 29, 10],
         ...,
         [ 5,  5, 83],
         [ 4,  3, 71],
         [ 2,  2, 66]],
 
        [[17, 20,  4],
         [22, 25,  9],
         [22, 25,  9],
         ...,
         [ 1,  1, 79],
         [ 2,  1, 75],
         [ 2,  1, 73]],
 
        ...,
 
        [[75, 56,  0],
         [76, 57,  0],
         [75, 56,  0],
         ...,
         [ 5, 14, 48],
         [ 7, 13, 50],
         [ 4, 10, 47]],
 
        [[75, 55,  0],
         [77, 57,  2],
         [76, 56,  1],
         ...,
         [ 5, 14, 48],
         [ 7, 13, 50],
         [ 3,  9, 46]],
 
        [[75, 55,  0],
         [76, 56,  1],
         [75, 55,  0],
         ...,
         [ 5, 14, 48],
         [ 8, 14, 51],
         [ 4, 10, 47]]], dtype=uint8),
 (720, 1280, 3))

In [ ]:
a = np.empty_like(img)
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [ ]:
## empty_like, zeros_like, ones_like, full_like(img, 255)
## 복사해서 새로운 열을 만듬.

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a.dtype, a.shape

(dtype('int64'), (5,))

In [ ]:
## np.arange(a,b,c) = range(a,b,c)
## np.arange는 타입도 지정가능

In [ ]:
np.random.rand()

0.7602872587204358

In [ ]:
np.random.randn()

-0.9855726220594108

In [ ]:
a = np.random.rand(2,3)

In [ ]:
b = np.random.randn(2,3)
a,b

(array([[0.29883307, 0.53093851, 0.57311268],
        [0.19361533, 0.78403061, 0.46603705]]),
 array([[ 0.86246327,  1.22829742,  0.53183755],
        [-0.21666612,  1.7962683 ,  1.55204432]]))

In [ ]:
a = np.arange(5)
b = a.astype('float')
a,b

(array([0, 1, 2, 3, 4]), array([0., 1., 2., 3., 4.]))

- reshape(newshape) : 차원변경
- numpy.reshape(nadrray, newshape)
- numpy.ravel(ndarray): 1차원 배열로 차원변경
- ndarray.T: 전치배열 - 판다스에도잇음

In [ ]:
a = np.arange(12)
a, a.reshape(3,4), a.reshape(3,4).T

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [ ]:
f = np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
g = np.arange(10).reshape(2,-1)
h = np.arange(100).reshape(2,-1)
i = np.arange(100).reshape(-1,4)
g,h, i

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
         82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
         98, 99]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
    

In [ ]:
f = np.zeros((2,3))
f.reshape(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
mylist = list(range(10))
for i in range(len(mylist)):
    mylist[i] = mylist[i]+1

In [ ]:
# 브로드캐스팅 연산 => 배열의 모든 요소에 동일하게 연ㅇ산.
a = np.arange(10)
a, a>2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([False, False, False,  True,  True,  True,  True,  True,  True,
         True]))

In [ ]:
## 배열간 연산의 규칙
## => 1. 배열의  shape가 동일
#    2. 하나의 배열이 1차원이고 1차원배열의 축의 길이가 같아야 한다.


In [ ]:
b = a.reshape(2,5)
a*b

ValueError: operands could not be broadcast together with shapes (10,) (2,5) 

In [ ]:
c = b.T
b*c.T

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
a = np.arange(12).reshape(3,4)
a[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [ ]:
b = a[::-1]

c = a>b
c

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

- numpy.hstack - 수평병합
- numpy.vstack - 수직병합
- numpy.concentrate(arrays, axis=0)- arrays를 지정한 축 기준으로 병ㅎ바
- nupy.stack(arrays, axis=0 or 1) 배열을 새로운 축으로 병합.


In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,130,10).reshape(4,3)

In [ ]:
a, b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]))

In [ ]:
c = np.stack((a,b), 0)
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
d = np.stack((a,b), 1)
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [ ]:
e = np.stack((a,b), 2)
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [ ]:
f = np.stack((a,b), -1) ## 마지막 축 번호. 2
f

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

- np.vsplit(array,indice) 수평으로 분리
- np.hsplit(array,indice) 수직으로 분리
- np.split(array, indice, axis=0) array axis로 분리


- ret = np.where(condition [, t, f])
- numpy.nozero(array) => 0이 아닌. isnotnull
- numpy.all(array [, axis]) 모든 요소가  True인지 검색
- numpy.any(array [, axis]) 어느 요소든지 True가 있는지 검색


In [ ]:
np.where(a>9, 99, a)
# 해당되는 것에 99 채우기

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 99, 99]])

In [ ]:
np.where(a>6, a, 0)
# 해당되지 않는 것에 0

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b = np.arange(12).reshape(3,4)

In [ ]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [ ]:
np.stack((coords[0],coords[1]),1),np.stack((coords[0],coords[1]),-1)

(array([[1, 3],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3]]),
 array([[1, 3],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3]]))

In [ ]:
np.stack((coords[0],coords[1]))

array([[1, 2, 2, 2, 2],
       [3, 0, 1, 2, 3]])

In [ ]:
z = np.array([0,1,2,0,1,2])
np.nonzero(z)
## index 반환
## 다차원이여도 coords는 차원수 만큼의 배열로 변환. 필요시 병합하여 좌표로 만들기.

(array([1, 2, 4, 5]),)

In [ ]:
t = np.array((True, True, True))
np.all(t)

np.True_

In [ ]:
t[1] = False
np.all(t) # ==> and

np.False_

In [ ]:
np.any(t) # ==> or

np.True_

In [ ]:
np.all(a), np.any(a)
## a는 0을 포함하고잇음


(np.False_, np.True_)

In [ ]:
np.all(a, 0), np.any(a, 1), np.any(a, -1)
## a는 0을 포함하고잇음
## 축을 지정하면 축 기준으로 만족하느지 반환.



(array([False,  True,  True]),
 array([ True,  True,  True,  True]),
 array([ True,  True,  True,  True]))

- np.sum(array[, axis])
- np.mean(array[, axis])
- np.amin(array[, axis]), np.min
- np.amax, mp.max

In [9]:
img = np.zeros((120,120))
img[25:45, :] = 45
img[55:65, :] = 115
img[85:95, :] = 160
img[:, 35:45] = 205
img[:, 75:85] = 255
cv2.imshow('Gray', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

